services:
  reactioncore:
    build: .
    container_name: reactioncore
    restart: unless-stopped
    environment:
      TOKEN: ${TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID}
    volumes:
      - /srv/reactioncore/storage:/app/src/Utilities/Storage